# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('event', models.IntegerField()),
            ],
        ),
    ]
