# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160418_2043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('user', 'event')]),
        ),
    ]
