# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='expired',
        ),
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
